name: Elixir CI

on: push

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    name: Linux OTP ${{matrix.pair.otp-version}} / Elixir ${{matrix.pair.elixir-version}}
    strategy:
      matrix:
        pair:
          - otp-version: '22.0'
            elixir-version: '1.9.0'
          #- otp-version: '23.0'
          #  elixir-version: '1.10'
          #- otp-version: '23.0'
          #  elixir-version: '1.11'

    steps:
    - uses: actions/checkout@v1
    - uses: erlef/setup-elixir@v1
      with:
        otp-version: ${{matrix.pair.otp-version}}
        elixir-version: ${{matrix.pair.elixir-version}}
    - name: Install Dependencies
      run: mix deps.get
    - name: Run Linting
      run: mix credo --strict
    - name: Run Tests
      env:
        RUNNING_CI: "true"
      run: mix test
  macos:
    runs-on: macos-latest
    name: MacOS OTP ${{matrix.pair.otp-version}} / Elixir ${{matrix.pair.elixir-version}}
    strategy:
      matrix:
        pair:
          - otp-version: '23.0'
            elixir-version: '1.11'
    steps:
    - uses: actions/checkout@v1
    - name: Install Elixir
      run: |
        brew update
        brew install elixir
    - name: Setup mix
      run: |
        mix local.hex --force
        mix local.rebar --force
    - name: Install Dependencies
      run: mix deps.get
    - name: Run Tests
      env:
        RUNNING_CI: "true"
      run: mix test
  freebsd:
    runs-on: macos-latest
    name: FreeBSD OTP ${{matrix.pair.otp-version}} / Elixir ${{matrix.pair.elixir-version}}
    strategy:
      matrix:
        pair:
          - otp-version: '23.0'
            elixir-version: '1.11'
    steps:
    - uses: actions/checkout@v2
    - name: Test in FreeBSD
      id: test
      uses: vmactions/freebsd-vm@v0.1.4
      with:
        usesh: true
        prepare: |
          pkg install -y curl
          pkg install -y elixir
        run: |
          elixir --version
          mix test