name: Elixir CI

on: push

jobs:
  ubuntu:
    runs-on: ubuntu-20.04
    name: Linux OTP ${{matrix.pair.otp-version}} / Elixir ${{matrix.pair.elixir-version}}
    strategy:
      matrix:
        pair:
          - otp-version: '25.0'
            elixir-version: '1.13.4'
          - otp-version: '26.0'
            elixir-version: '1.14.5'
          - otp-version: '26.0'
            elixir-version: '1.15.2'
    steps:
    - uses: actions/checkout@v1
    - uses: erlef/setup-elixir@v1
      with:
        otp-version: ${{matrix.pair.otp-version}}
        elixir-version: ${{matrix.pair.elixir-version}}
    - name: Install Dependencies
      run: mix deps.get
    - name: Run Linting
      run: mix credo --strict
    - name: Run Tests
      env:
        RUNNING_CI: "true"
      run: mix test --exclude no_ci
  macos:
    runs-on: macos-latest
    name: MacOS OTP ${{matrix.pair.otp-version}} / Elixir ${{matrix.pair.elixir-version}}
    strategy:
      matrix:
        pair:
          - otp-version: '25.0'
            elixir-version: '1.13.4'
    steps:
    - uses: actions/checkout@v1
    - name: Install Elixir
      run: |
        brew update
        brew install elixir
    - name: Setup mix
      run: |
        mix local.hex --force
        mix local.rebar --force
    - name: Install Dependencies
      run: mix deps.get
    - name: Run Tests
      env:
        RUNNING_CI: "true"
      run: mix test --exclude no_ci
